/* GENERATED by scripts/build-og-simple-systems.mjs. Do not edit by hand.
   The hash is the card's content, so a new card is a new URL and no
   scraper can serve a cached copy of the old one. */
export const OG_IMAGE = "/images/og-simple-systems.c30f79819f.jpg";
