import puppeteer from "puppeteer-core";
const [out] = process.argv.slice(2);
const browser = await puppeteer.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: true, args: ["--hide-scrollbars"] });
const page = await browser.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
await page.setViewport({ width: 1440, height: 900 });
await page.goto("http://127.0.0.1:4321/about", { waitUntil: "networkidle0" });
await page.evaluate(() => document.querySelector("#believe-h").scrollIntoView({ behavior: "instant", block: "start" }));
await new Promise((r) => setTimeout(r, 1800));
await page.screenshot({ path: `${out}/orbit-rest.png` });
await page.click('[data-node="2"]');
await new Promise((r) => setTimeout(r, 1400));
await page.screenshot({ path: `${out}/orbit-active.png` });
await page.setViewport({ width: 400, height: 860 });
await page.evaluate(() => document.querySelector("#believe-h").scrollIntoView({ behavior: "instant", block: "start" }));
await new Promise((r) => setTimeout(r, 1200));
await page.screenshot({ path: `${out}/orbit-mobile.png`, fullPage: false });
console.log(JSON.stringify({ errors }));
await browser.close();
